### ISSUE TITLE
Can't Pod Install

### ISSUE THREAD

**Issue by farazhassan** [instructure/instructure-ios#1]
instructure:ios-podspecs.git is not available/accessible.

**Comment by bootstraponline** [comment]
I'm checking to see if I can make that repo available.

**Comment by farazhassan** [comment]
Any success? Carthage and Pod, both fail and I can't move forward without it.

**Comment by farazhassan** [comment]
@bootstraponline Not doing it then I suppose?

**Comment by laynemoseley** [comment]
We will be doing a release sometime in the future that will fix this issue. No date is planned at this time though.

**Comment by bootstraponline** [comment]
https://github.com/instructure/ios-podspecs is now public. The pod install step will probably still fail until the open source repo is synced again (no ETA).

**Comment by laynemoseley** [comment]
If everything goes as planned, there will be a new release on Monday.

**Comment by laynemoseley** [comment]
This has been resolved.

**Comment by madmann8** [comment]
@laynemoseley sorry, where can canvaskeymaster-ios be accessed?
