### ISSUE TITLE
Failed to load bundle: Metro Bundler encountered internal error

### ISSUE THREAD

**Issue by TannerJuby1** [instructure/instructure-ios#10]
When attempting to run the project, I keep receiving the `Failed to load bundle with error: Metro Bundler has encountered internal error, please check your terminal output for more details.`

When I look at the terminal I see the error: `Error: 'fsevents' unavailable (this watcher can only be used on Darwin)`

I ran the `./setup.sh` script as instructed in the readme, but is there something else that I am missing?

**Comment by bootstraponline** [comment]
strange, we're in the process of setting up CI for the open source apps. That may help with issues like this.

**Comment by bootstraponline** [comment]
It'll be this sprint so probably two weeks.

**Comment by TannerJuby1** [comment]
Okay thanks!

**Comment by TannerJuby1** [comment]
I was able to get this issue resolved by running `npm install fsevents` in my terminal prior to building and running. Hopefully that will help with your CI.

**Comment by bootstraponline** [comment]
awesome. I think once the public CI is setup then people can copy the commands. :)

I'll close the issue since it's working.

**Comment by bootstraponline** [comment]
I ran into the same issue building student app. 🙂

**Comment by TannerJuby1** [comment]
Did running `npm install fsevents` resolve the issue?

**Comment by bootstraponline** [comment]
yep 🙂

**Comment by TannerJuby1** [comment]
Sweet! :)
