### ISSUE TITLE
Error on compiling RN

### ISSUE THREAD

**Issue by huangdengpan** [instructure/instructure-ios#13]
Hi,
I am trying to compile Canvas APP, an error shows the picture as below.
Does anyone know the way to fix it ?
[error][tid:com.facebook.react.JavaScript] Cannot call a class as a function

![image](https://user-images.githubusercontent.com/16663404/41917369-c894eb26-798c-11e8-92ea-b51d6c8b7700.png)

**Comment by huangdengpan** [comment]
The calss RN Profile
Unhandled JS Exception: Cannot call a class as a function, stack:
_classCallCheck@105452:24
Connect(Profile)@105546:24

 let Connected =  connect(mapStateToProps, {...Actions})(Profile)
export default Connected

**Comment by laynemoseley** [comment]
Are you running the app through Xcode?

**Comment by huangdengpan** [comment]
I am running the app with Xcode 9.2, must it be v9.3?

**Comment by laynemoseley** [comment]
yes, as noted in the readme.

**Comment by huangdengpan** [comment]
Thank you very much, if I update Xcode , it would be v9.4.1, does it match the environment?

**Comment by laynemoseley** [comment]
We haven't updated to use Xcode 9.4 yet, but it should work.

**Comment by huangdengpan** [comment]
Thank you, I am going to update Xcode and try it again. Have a nice day !

**Comment by huangdengpan** [comment]
@laynemoseley 
Hi man,
After updating the Xcode to v9.4.1 and Nodejs to v10.4.1, the error still be there.
Is there any steps I forgot to do ?

`Printing description of message:
Unhandled JS Exception: Cannot call a class as a function, stack:
_classCallCheck@105335:24
Connect(Profile)@105429:24
<unknown>@106988:39
loadModuleImplementation@127:12
<unknown>@105116:25
loadModuleImplementation@127:12
<unknown>@104730:29
loadModuleImplementation@127:12
<unknown>@1311:31
loadModuleImplementation@127:12
guardedLoadModule@79:45
global code@186793:9`

**Comment by laynemoseley** [comment]
I'm not sure, this is not an error that I have ever seen before.

Did you make sure to do a `pod install` before `yarn` ?

**Comment by huangdengpan** [comment]
Hi Mr.Moseley,
Thank you for your kind help.
I updated the environment, and reinitialized the configuration, but met the error as below.
As you know, we have different development habit. It looks like that the RN modules are not registered, so I do not know how to run the RN module. My friends who worked on IOS development do not know the way to solve it.
Would you please help me have a look ?Thank you!
**And if you have time, please give us a detailed tutorial. I really need it.** Have a good night !

![image](https://user-images.githubusercontent.com/16663404/42302141-ec1a59a8-804b-11e8-8b56-4a9b0d501583.png)
