### ISSUE TITLE
App throws red screen with React Native error when tried to create discussion

### ISSUE THREAD

**Issue by vdharankar** [instructure/instructure-ios#18]
I have setup Canvas with self hosted server and able to run the iOS app successfully with the same self hosted server , but all throws React Native error when tried to create a new discussion via course page. attached is the screen shot, it generally tells nothing much, a pointer in right direction will be a great help.

Thanks
<img width="377" alt="screen shot 2018-08-08 at 10 45 05 pm" src="https://user-images.githubusercontent.com/12953988/43917374-c97f3d0c-9c2d-11e8-99bd-8b63c3dd9dc6.png">

**Comment by laynemoseley** [comment]
Thanks!

**Comment by laynemoseley** [comment]
I'll take a look today

**Comment by armstrongnate** [comment]
Have you made any code changes to the `rn/Teacher/` directory by chance? Deleted some code or removed some files by chance?

**Comment by armstrongnate** [comment]
There's a file called `zss-rich-text-editor.html`. If you `cmd+shift+o` you can find it in Xcode. Can you verify that it exists and that it is being compiled with CanvasCore framework?

**Comment by armstrongnate** [comment]
It lives in `rn/Teacher/lib/zss-rich-text-editor.html`.

**Comment by armstrongnate** [comment]
If you press <kbd>CMD</kbd>+<kbd>D</kbd> in the simulator the React Native debug window will show and you can tap `Debug JS Remotely` which will launch a Chrome debugger. If you view the console in that chrome window when the error occurs, there might be more info about that the error. 

Would you mind posting the logs from the chrome debugger here?

**Comment by vdharankar** [comment]
Yes that file is present already , how do you think I can make sure if its being bundled or not ?
Here is more from JS console in chrome.
<img width="599" alt="screen shot 2018-08-21 at 1 34 05 pm" src="https://user-images.githubusercontent.com/12953988/44388900-003c1a00-a547-11e8-9f8d-5ddd579df9d7.png">

**Comment by vdharankar** [comment]
problem is , it doesn't even point to a file , so its pretty hard to guess where and whats going wrong.

**Comment by armstrongnate** [comment]
@vdharankar Can you take a look at this?

https://github.com/instructure/instructure-ios/issues/24#issuecomment-415683160

Have you changed any of the project bundle identifiers? That issue is identical to yours and was resolved by using the original bundle identifiers.
