### ISSUE TITLE
Has anyone built it successfully?

### ISSUE THREAD

**Issue by farazhassan** [instructure/instructure-ios#2]
Some of the dependencies are in private repositories with no public access, has anyone(out of instructure) built this code successfully yet?

**Comment by bootstraponline** [comment]
The app doesn't build using only the public code. There have been conversations about fixing this. There's no ETA on if/when this will change.

**Comment by farazhassan** [comment]
I can't really do anything with this code in that case ..

**Comment by laynemoseley** [comment]
You should be able to build successfully now. If you can't, please let me know. :)
