### ISSUE TITLE
Showing red error screen while reply on an announcement

### ISSUE THREAD

**Issue by apekshit-capgemini** [instructure/instructure-ios#24]
### Issue Description
While replying on an announcement post, rather than showing the reply screen it is showing react-native red screen of `unhanded promise rejection` 
<img width="487" alt="screen shot 2018-08-07 at 8 03 24 pm" src="https://user-images.githubusercontent.com/42271052/43958304-85e59af0-9cc8-11e8-8159-a3c4dc932221.png">

**For testing it on actual device, I have updated App ID in the application.**

### Steps to Reproduce
Open application -> Login with valid user -> Goto course -> Tap on announcement -> Tap on existing announcement -> Tap on reply link/button

### Environment
Platform(s) (iOS, Android, or both?): **Checked on IOS**
Device info (Simulator/Device? OS version? Debug/Release?): **Simulator and Device both / iOS 11.4 / Debug**

**Comment by armstrongnate** [comment]
Have you made any code changes to the `rn/Teacher/` directory by chance? Deleted some code or removed some files by chance?

**Comment by apekshit-capgemini** [comment]
### Here are the logs from the console:

`ExceptionsManager.js:73 Unhandled promise rejection Error: ENOENT: no such file or directory, open 'undefined'
    at createErrorFromErrorData (NativeModules.js:123)
    at NativeModules.js:80
    at MessageQueue.__invokeCallback (MessageQueue.js:346)
    at MessageQueue.js:132
    at MessageQueue.__guard (MessageQueue.js:262)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:131)
    at debuggerWorker.js:72
reactConsoleErrorHandler @ ExceptionsManager.js:73
console.error @ YellowBox.js:71
(anonymous) @ es6.promise.js:110
module.exports @ _perform.js:3
(anonymous) @ es6.promise.js:104
(anonymous) @ JSTimers.js:301
_callTimer @ JSTimers.js:154
_callImmediatesPass @ JSTimers.js:202
callImmediates @ JSTimers.js:470
__callImmediates @ MessageQueue.js:275
(anonymous) @ MessageQueue.js:140
__guard @ MessageQueue.js:262
flushedQueue @ MessageQueue.js:139
invokeCallbackAndReturnFlushedQueue @ MessageQueue.js:135
(anonymous) @ debuggerWorker.js:72`

### Attaching its screenshots as well:
<img width="1284" alt="screen shot 2018-08-14 at 3 12 12 pm" src="https://user-images.githubusercontent.com/42271052/44084816-60cedfd2-9fd5-11e8-8048-3ccbbcc94145.png">

**I saw your comment on another issue ([issue-18](https://github.com/instructure/instructure-ios/issues/18)) regarding this same error on "discussion screen", there you mentioned to check for `zss-rich-text-editor.html` file. Yes it is there in the mentioned path and used in CanvasCore -> React Native Modules -> CanvasWebViewContainer.m -> -setSource method in XCode.**

**Comment by armstrongnate** [comment]
@apekshit-capgemini Hmm that error is not super useful and I haven't been able to reproduce yet. If you want to provide me with some credentials to test with you can email me at `narmstrong`@`instructure.com`. Also, are you using a fork of this repro? Maybe I should try on your fork, if so.

**Comment by sijones1886** [comment]
@armstrongnate  we needed to have some internal admin sorted to share the code and credentials with you, will be available tomorrow for you to view @apekshit-capgemini  I have sent appropriate confirmation to you

**Comment by vdharankar** [comment]
@apekshit-capgemini did you got this sorted ? Any solution ?

**Comment by armstrongnate** [comment]
I have not yet received test credentials from @apekshit-capgemini.

**Comment by vdharankar** [comment]
Hey @armstrongnate I don't work with @apekshit-capgemini so no idea, but what credentials you need ? I might be able to provide or do you want me to add to our fork ? So that you can test the code which I have ?

**Comment by vdharankar** [comment]
@armstrongnate please check here https://github.com/vdharankar/blitzprep

**Comment by apekshit-capgemini** [comment]
This issue is coming due to changing the bundle identifier of CanvasCore and CanvasKeyMaster framework, I have put instructure bundle id in CanvasCore and CanvasKeyMaster framework as it is and this issue is not occurred after that.

**Comment by vdharankar** [comment]
@apekshit-capgemini won't it create issue while creating release and signing it ? @armstrongnate

**Comment by vdharankar** [comment]
Never mind , I solved that issue as well , your answer was a hint , searched for CanvasCore bundle id in code and replaced it with my own, that way I don't need the original bundle ids, btw for me it was still crashing with original bundle ids.
