### ISSUE TITLE
Showing red error screen while adding a new announcement

### ISSUE THREAD

**Issue by apekshit-capgemini** [instructure/instructure-ios#25]
### Issue Description
While add a new announcement post, it is showing react-native red screen of `unhanded promise rejection`

<img width="487" alt="screen shot 2018-08-07 at 8 03 24 pm" src="https://user-images.githubusercontent.com/42271052/43958637-ba34ecb0-9cc9-11e8-88b4-6f84574554f4.png">

**Note: For testing it on actual device, I have updated App ID in the application.**

### Steps to Reproduce
Open application -> Login with valid user -> Goto course -> Tap on announcement -> Tap on + icon

### Environment
Platform(s) (iOS, Android, or both?): **Checked on IOS**
Device info (Simulator/Device? OS version? Debug/Release?): **Simulator and Device both / iOS 11.4 / Debug**

**Comment by armstrongnate** [comment]
If you press <kbd>CMD</kbd>+<kbd>D</kbd> in the simulator the React Native debug window will show and you can tap `Debug JS Remotely` which will launch a Chrome debugger. If you view the console in that chrome window when the error occurs, there might be more info about that the error. 

Would you mind posting the logs from the chrome debugger here?

**Comment by apekshit-capgemini** [comment]
This issue is coming due to changing the bundle identifier of CanvasCore and CanvasKeyMaster framework, I have put instructure bundle id in CanvasCore and CanvasKeyMaster framework as it is and this issue has been resolved after that.
